--CREATING TABLE TO RECORDS THE ACTIONS OR MODIFICATIONS GOING ON ALL DATABASES

--DISABLE TRIGGER DDL_TRIGGER_CREATE_TABLE ON DATABASE;
GO
DISABLE TRIGGER DDL_TRIGGER_DROP_TABLE ON DATABASE;
DISABLE TRIGGER DDL_TRIGGER_ALL_SERVER ON ALL SERVER;
DISABLE TRIGGER ServerDDLEventTrigger ON ALL SERVER;
ENABLE TRIGGER ServerDDLEventTrigger ON ALL SERVER;
DROP TABLE DBO.DDLEVENTLOG;
CREATE TABLE DDLEventLog (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    EventTime DATETIME DEFAULT GETDATE(),
    EventType NVARCHAR(100),
    DatabaseName NVARCHAR(255),
    SchemaName NVARCHAR(255),
    ObjectName NVARCHAR(255),
    LoginName NVARCHAR(255),
    EventData XML
);