--CREATING EVENT GROUP TRIGGER
ALTER TRIGGER DDL_TRIGGER_FUNC_EVENTS
ON DATABASE
FOR DDL_FUNCTION_EVENTS
AS
BEGIN
PRINT'CREATION, ALTER,DROP OF FUNCTIONS ARE NOT ALLOWED IN THIS DATABASE';
ROLLBACK TRANSACTION;
END

GO
--CREATING FUNCTION IN DATABASE WHICH IS NOT ALLOWED BY TRIGGER
CREATE FUNCTION FUNC_CREATE_1(@A INT , @B INT)
RETURNS INT
AS
BEGIN
DECLARE @RESULT INT;
SET @RESULT=@A+@B;
RETURN @RESULT;
END

GO

--TRING TO DELETE ALREADY EXISTED FUNCTION , TRIGGER WON'T ALLOW TO DO SO
DROP FUNCTION MULTIPLY;