--CREATING DDL TRIGGER THAT WONOT ALLOW TO CREATE TABLES IN DATABASE 
USE SQLSERVERPRACTICE;
GO
ALTER TRIGGER DDL_TRIGGER_CREATE_TABLE
ON DATABASE
FOR CREATE_TABLE
AS
BEGIN
PRINT 'CREATION OF TABLE IS NOT ALLOWED';
ROLLBACK TRANSACTION;
END

GO 
--CREATING TABLE IN DATABASE WHERE CREATION OF TABLE NOT ALLOWED
CREATE TABLE TESTING_TABLE_3
(NAME VARCHAR(25),
ID INT);

--DELETING TABLES

DROP TABLE IF EXISTS TESTING_TABLE_2;
