
--USE SqlServerPractice; GO ;
--creating trigger that won't allow altering table, deletion of table in the database
CREATE TRIGGER DDL_TRIGGER_DROP_TABLE
ON DATABASE
FOR ALTER_TABLE,DROP_TABLE
AS
BEGIN
PRINT'ALTER OR ELETING THE TABLE IS NOT ALLOWED';
ROLLBACK TRANSACTION;
END

GO
--DELETING THE TABLE WHICH IS NOT ALLOWED IN THIS DATABASE
DROP TABLE TESTING_TABLE;

--ALTERING THE TABLE BY ADDING COLUMN TO IT,
--BUT ALTER_TABLE IS NOT ALLOWED IN THIS DATABASE DUE TO TRIGGER CREATION
ALTER TABLE EMPLOYEE_DETAILS
ADD  PERFORMANCE VARCHAR(50);
