--CREATING TRIGGER ON ALL DATABSES PRESENT IN SERVER
CREATE TRIGGER DDL_TRIGGER_ALL_SERVER
ON ALL SERVER
FOR DROP_TABLE
AS
BEGIN
PRINT'DELETION OF TABLES ARE NOT ALLOWED IN ALL THE DATABASES(ALL SERVER)';
ROLLBACK TRANSACTION;
END
GO
USE employeepayroll;
GO
DROP TABLE UserDeatails;