--CREATING TABLE TO BACKUP THE UPDATED VALUES IN EMPLOYEE_DETAILS TABLE

CREATE TABLE TRIGGER_TABLE_UPDATE
(
EMP_ID INT,
FIELD_NAME VARCHAR(20),
OLD_VALUE VARCHAR(30),
NEW_VALUE VARCHAR(30),
UPDATED_TIME DATETIME
);