--CREATING TRIGGER FOR UPDATE OPERATION ON EMPLOYEE_DETAILS

CREATE TRIGGER DML_TRIGGER_UPDATE
ON EMPLOYEE_DETAILS
AFTER UPDATE
AS
BEGIN
IF UPDATE(NAME)
INSERT INTO TRIGGER_TABLE_UPDATE(EMP_ID,FIELD_NAME,OLD_VALUE,NEW_VALUE,UPDATED_TIME)
SELECT I.EMP_ID,'NAME',D.NAME,I.NAME,GETDATE() FROM INSERTED I JOIN DELETED D ON I.EMP_ID=D.EMP_ID;

IF UPDATE(EMAIL)
INSERT INTO TRIGGER_TABLE_UPDATE(EMP_ID,FIELD_NAME,OLD_VALUE,NEW_VALUE,UPDATED_TIME)
SELECT I.EMP_ID,'EMAIL',D.EMAIL,I.EMAIL,GETDATE() FROM INSERTED I JOIN DELETED D ON I.EMP_ID=D.EMP_ID;

IF UPDATE(GENDER)
INSERT INTO TRIGGER_TABLE_UPDATE(EMP_ID,FIELD_NAME,OLD_VALUE,NEW_VALUE,UPDATED_TIME)
SELECT I.EMP_ID,'GENDER',D.GENDER,I.GENDER,GETDATE() FROM INSERTED I JOIN DELETED D ON I.EMP_ID=D.EMP_ID;

IF UPDATE(DATEOFBIRTH)
INSERT INTO TRIGGER_TABLE_UPDATE(EMP_ID,FIELD_NAME,OLD_VALUE,NEW_VALUE,UPDATED_TIME)
SELECT I.EMP_ID,'DATE_of_BIRTH',D.DateOfBirth,I.DateOfBirth,GETDATE() FROM INSERTED I JOIN DELETED D ON I.EMP_ID=D.EMP_ID;

IF UPDATE(PACKAGE)
INSERT INTO TRIGGER_TABLE_UPDATE(EMP_ID,FIELD_NAME,OLD_VALUE,NEW_VALUE,UPDATED_TIME)
SELECT I.EMP_ID,'PACKAGE',D.Package,I.Package,GETDATE() FROM INSERTED I JOIN DELETED D ON I.EMP_ID=D.EMP_ID;

IF UPDATE(ADDRESS)
INSERT INTO TRIGGER_TABLE_UPDATE(EMP_ID,FIELD_NAME,OLD_VALUE,NEW_VALUE,UPDATED_TIME)
SELECT I.EMP_ID,'ADDRESS',D.Address,I.Address,GETDATE() FROM INSERTED I JOIN DELETED D ON I.EMP_ID=D.EMP_ID;

if update(phone_number)
INSERT INTO TRIGGER_TABLE_UPDATE(EMP_ID,FIELD_NAME,OLD_VALUE,NEW_VALUE,UPDATED_TIME)
SELECT I.EMP_ID,'phone_number',D.phone_number,I.phone_number,GETDATE() FROM INSERTED I JOIN DELETED D ON I.EMP_ID=D.EMP_ID;

END