
--PERFORMING INSERTION AND DELETION ON 'EMPLOYEE_DETAILS' TABLE AND 
--CHECKING WHERETHER THE ACTION ARE REFLECTING TO 'TRG_INS_DEL' TABLE OR NOT

INSERT INTO Employee_Details(NAME,GENDER,EMAIL,DateOfBirth,PACKAGE)
VALUES('MYTHILI','F','MYTHILI@EMAIL.COM','2003-10-23',600000);

INSERT INTO Employee_Details(NAME,GENDER,EMAIL,DateOfBirth,PACKAGE)
VALUES('sITA','F','SITA@EMAIL.COM','2000-01-01',900000),
('JANAKI','F','JANAKI@EMAIL.COM','2000-10-10',800000);

DELETE FROM Employee_Details WHERE NAME='RAJESH';

DELETE FROM Employee_Details WHERE PACKAGE<450000;

SELECT * FROM TGR_INS_DEL;

INSERT INTO Employee_Details(NAME,GENDER,EMAIL,DateOfBirth,PACKAGE)
VALUES('BUMIJA','F','BUMIJA@EMAIL.COM','2000-01-01',900000),
('JANASI','F','JANASI@EMAIL.COM','2000-10-10',800000);

DELETE FROM Employee_Details WHERE EMP_ID=10;
