--Renaming the index
EXEC SP_RENAME  'IX_SALESMAN','SALES_PER',N'INDEX';

EXEC SP_RENAME N'IX_SALESMAN',N'SALES_PER',N'INDEX';

EXEC SP_RENAME @objname =  N'IX_SALESMAN',@NEWNAME=N'SALES_PER',@OBJTYPE=N'INDEX';