--Using IF ELSE statements in stored Procedures
CREATE PROC spIf_Else
@condition int
AS
IF @condition<100
	BEGIN
		PRINT 'VALUE ENTERED IS BELOW 100';
	END
ELSE
	BEGIN
		PRINT 'VALUE ENTERED IS GREATER THAN OR EQUAL 100';
	END

--EXECUTING STORED PROCEDURE HAVING 'IF ELSE' CONDITIONS
EXEC spIf_Else 200;
EXEC spIf_Else 20;