
--Creating user defined function named multiply with two parameters
CREATE FUNCTION MULTIPLY(@VALUE1 INT,@VALUE2 INT)
RETURNS  INT 
AS
BEGIN 
DECLARE @RESULT INT;
SET @RESULT=@VALUE1*@VALUE2;
RETURN @RESULT;
END

--SELECT DBO.MULTIPLY(3,6) AS MULTIPLICATION;