--Creating Multi statement Table Valued Function
CREATE FUNCTION MSTVF()
RETURNS @MSTVF_TABLE TABLE
(
ID INT,
NAME VARCHAR(20),
ADDRESS VARCHAR(40)
)
AS
BEGIN
	
	INSERT INTO @MSTVF_TABLE
	SELECT EMP_ID,Name,Address FROM Employee_Details;
	INSERT INTO @MSTVF_TABLE
	SELECT Cust_ID,Cust_Name,City FROM CUSTOMERS;
	RETURN;
END

SELECT * FROM  MSTVF();