--CREATING FUNCTION THAT RETURNS THE TABLE WITH SALARIES GREATERTHAN THE GIVEN INPUT SALARY
CREATE FUNCTION UDF_HIGH_SALARY(@SALARY DECIMAL)
RETURNS TABLE
AS

RETURN
SELECT EMP_ID,NAME,Package  FROM Employee_Details WHERE Package>@SALARY;

EXEC sp_helptext 'UDF_HIGH_SALARY';

SELECT * FROM DBO.UDF_HIGH_SALARY(600000);

SELECT EMP_ID,NAME FROM DBO.UDF_HIGH_SALARY(600000);